apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service internally
      targetPort: 80  # Port on the pods where traffic is forwarded
